{
    'name': 'real estate',
    'version': '1.0',
    'summary': 'it is just an testing module',
    'discription': '',
    'website': 'https://strataprop.com/',
    'author': 'Mihir nayak',
    'category': 'Sales',
    'depends': [],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rules2.xml',
        'security/res_groups2.xml',
        'wizard/print_all_property_view.xml',
        'views/estate_view.xml',
        'views/estate_type_view.xml',
        'views/estate_tags_view.xml',
        'views/estate_offer_view.xml',
        'views/res_users_view.xml',
        'reports/estate_property_report.xml',
        'reports/estate_user_property_report.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False
}
